// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2LuiBTlPyjgZ50toZxVTJqrynZcejgdk',
    appId: '1:382058754313:web:a2603739dc894443f8a3d8',
    messagingSenderId: '382058754313',
    projectId: 'fuel-flow-f7882',
    authDomain: 'fuel-flow-f7882.firebaseapp.com',
    storageBucket: 'fuel-flow-f7882.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd-4dovLCv_Om_lI_jI4M7KXGCTZAajto',
    appId: '1:382058754313:android:03435305b4cef70df8a3d8',
    messagingSenderId: '382058754313',
    projectId: 'fuel-flow-f7882',
    storageBucket: 'fuel-flow-f7882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wTHTH7auccRIPWlinUrcsnvuHIBBumk',
    appId: '1:382058754313:ios:39e7a8d6455f2590f8a3d8',
    messagingSenderId: '382058754313',
    projectId: 'fuel-flow-f7882',
    storageBucket: 'fuel-flow-f7882.firebasestorage.app',
    iosBundleId: 'com.example.fuelflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wTHTH7auccRIPWlinUrcsnvuHIBBumk',
    appId: '1:382058754313:ios:39e7a8d6455f2590f8a3d8',
    messagingSenderId: '382058754313',
    projectId: 'fuel-flow-f7882',
    storageBucket: 'fuel-flow-f7882.firebasestorage.app',
    iosBundleId: 'com.example.fuelflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2LuiBTlPyjgZ50toZxVTJqrynZcejgdk',
    appId: '1:382058754313:web:7ce980734a0a9075f8a3d8',
    messagingSenderId: '382058754313',
    projectId: 'fuel-flow-f7882',
    authDomain: 'fuel-flow-f7882.firebaseapp.com',
    storageBucket: 'fuel-flow-f7882.firebasestorage.app',
  );
}
